apply plugin: 'com.android.application'


android {

    compileSdkVersion 28


    defaultConfig {

        applicationId "com.l101.volumefloat"

        minSdkVersion 19

        targetSdkVersion 26


        versionCode 1

        versionName "1.0"


        ndk {
            abiFilters "armeabi-v7a"
        }


    }


    buildTypes {


        debug {

            minifyEnabled false

        }


        release {

            minifyEnabled false

        }


    }


    compileOptions {

        sourceCompatibility JavaVersion.VERSION_1_8

        targetCompatibility JavaVersion.VERSION_1_8

    }

}


dependencies {

}