apply plugin: 'com.android.application'


android {

    compileSdkVersion 28


    defaultConfig {

        applicationId "com.l101.volumefloat"

        minSdkVersion 19

        targetSdkVersion 26

        def appVersionCode = project.hasProperty("APP_VERSION_CODE")
                ? Integer.valueOf(project.property("APP_VERSION_CODE"))
                : 1

        def appVersionName = project.hasProperty("APP_VERSION_NAME")
                ? project.property("APP_VERSION_NAME").toString()
                : "1.0"

        versionCode appVersionCode

        versionName appVersionName


    }


    signingConfigs {

        release {

            if (project.hasProperty("RELEASE_STORE_FILE")) {

                storeFile file(
                        project.property("RELEASE_STORE_FILE")
                )

                storePassword project.property(
                        "RELEASE_STORE_PASSWORD"
                )

                keyAlias project.property(
                        "RELEASE_KEY_ALIAS"
                )

                keyPassword project.property(
                        "RELEASE_KEY_PASSWORD"
                )
            }
        }
    }


    buildTypes {


        debug {

            minifyEnabled false

        }


        release {

            minifyEnabled false

            if (project.hasProperty("RELEASE_STORE_FILE")) {

                signingConfig signingConfigs.release

            }

        }


    }


    compileOptions {

        sourceCompatibility JavaVersion.VERSION_1_8

        targetCompatibility JavaVersion.VERSION_1_8

    }

}


dependencies {

}
